repos:
  - repo: local
    hooks:
      - id: run-tests-locally
        name: Run tests

        entry: bash
        language: system
        pass_filenames: false

        stages: [commit, push]
        args:
          - -c
          - |
            cd backend
            poetry shell
            poetry run pytest
