// should contain all the countries that are available in vpngate.net except RUSSIA, IRAN, NORTH KOREA, CHINA, ... ?

// format example - Japan: 'JP',

export const availableCountries: Record<string, string> = {
  Japan: 'JP',
  UnitedStates: 'US',
  Germany: 'DE',
  France: 'FR',
  Netherlands: 'NL',
  Canada: 'CA',
  Singapore: 'SG',
  HongKong: 'HK',
  UnitedKingdom: 'GB',
  Switzerland: 'CH',
  Sweden: 'SE',
  Norway: 'NO',
  Denmark: 'DK',
  Belgium: 'BE',
  Finland: 'FI',
  CzechRepublic: 'CZ',
  Italy: 'IT',
  Spain: 'ES',
  Poland: 'PL',
  Australia: 'AU',
  SouthKorea: 'KR',
  Taiwan: 'TW',
  Romania: 'RO',
  Turkey: 'TR',
  Ukraine: 'UA',
  Luxembourg: 'LU',
  Austria: 'AT',
  Hungary: 'HU',
  Slovakia: 'SK',
  Bulgaria: 'BG',
  Lithuania: 'LT',
  Latvia: 'LV',
  Estonia: 'EE',
  Croatia: 'HR',
  Moldova: 'MD',
  BosniaAndHerzegovina: 'BA',
  Serbia: 'RS',
  Slovenia: 'SI',
  Montenegro: 'ME',
  Macedonia: 'MK',
  Albania: 'AL',
  Cyprus: 'CY',
  Malta: 'MT',
  Iceland: 'IS',
  Andorra: 'AD',
  Liechtenstein: 'LI',
  Gibraltar: 'GI',
  FaroeIslands: 'FO',
  Monaco: 'MC',
  SanMarino: 'SM',
  VaticanCity: 'VA',
}
