name: Backend CI

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"
  pull_request:
    branches: ["main"]
    paths:
      - "backend/**"

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.4.2

      - name: Install dependencies
        run: |
          cd backend
          poetry install

      - name: Check imports with isort
        run: |
          cd backend
          poetry run isort --check-only .

      - name: Run tests with coverage
        run: |
          cd backend
          poetry run pytest --maxfail=1 --disable-warnings --cov=. --cov-report=term-missing

      - name: Check server startup (optional)
        run: |
          cd backend
          poetry run uvicorn main:app --port 8001 &
          SERVER_PID=$!
          sleep 3
          curl -f http://127.0.0.1:8001/ || (echo "Server not responding" && exit 1)
          kill $SERVER_PID
          wait $SERVER_PID || true
