name: Backend CI

on:
  push:
    branches:
      - "*"
    paths:
      - "backend/**"
  pull_request:
    branches: ["main"]
    paths:
      - "backend/**"

jobs:
  lint:
    name: Lint Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.4.2

      - name: Install dependencies
        run: |
          cd backend
          poetry install --no-interaction --no-ansi
        env:
          POETRY_NO_INTERACTION: 1

      - name: Check code formatting with Black
        env:
          POETRY_NO_INTERACTION: 1
        run: |
          cd backend
          poetry run black --check --no-ansi .

      - name: Check isort ordering
        run: |
          cd backend
          poetry run isort --check-only .
