name: Frontend CI

on:
  push:
    branches:
      - "*"
    paths:
      - "frontend/**"
  pull_request:
    branches: ["main"]
    paths:
      - "frontend/**"

jobs:
  frontend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Или другая версия

      - name: Install dependencies
        run: |
          cd frontend
          npm install
          # или yarn install

      - name: Run lint / build / test
        run: |
          cd frontend
          npm run lint
          npm run build
          npm run test
